spring:
  application:
    name: bookmanagement
  datasource:
    url: jdbc:postgresql://localhost:5432/book_management
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  exchange:
    name: user-order-exchange
  queue:
    name: order-queue
  routing:
    key: user-order-key

server:
  port: 8081